fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
        exclude: ^helm/
      - id: debug-statements
      - id: name-tests-test
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: pretty-format-toml
        exclude: ^poetry.lock
        args: ["--autofix"]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.20.0
    hooks:
      - id: toml-sort
        exclude: ^poetry.lock
        args: ["--all", "--in-place"]
